### ISSUE TITLE
Cannot delete objects by filter

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-weaviate#13]
### Expected Behavior

Something seems wrong in this part:

https://github.com/kestra-io/plugin-weaviate/blob/master/src/main/java/io/kestra/plugin/weaviate/Delete.java#L101-L106

https://weaviate.io/developers/weaviate/manage-data/delete#delete-multiple-objects 

### Actual Behaviour

Reproducer: first insert movies

```yaml
id: weaviate-insert
namespace: dev

inputs:
  - name: weaviateClusterUrl
    type: STRING
    defaults: https://demo-c0geejdk.weaviate.network
  - name: weaviateApiKey
    type: STRING
    defaults: "{{ secret('WEAVIATE_API_KEY') }}"


tasks:
  - id: insertWeaviateMovies
    type: io.kestra.plugin.weaviate.BatchCreate
    url: "{{ inputs.weaviateClusterUrl }}"
    apiKey: "{{ inputs.weaviateApiKey }}"
    className: Movies
    objects:
      - name: "The Shawshank Redemption"
        description: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion."
        category: "Drama"
      - name: "The Godfather"
        description: "Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger."
        category: "Crime"
      - name: "The Dark Knight"
        description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
        category: "Action"
```

### Steps To Reproduce

now try to delete Shawshank:

```yaml
id: weaviate-delete
namespace: dev

inputs:
  - name: weaviateClusterUrl
    type: STRING
    defaults: https://demo-c0geejdk.weaviate.network
  - name: weaviateApiKey
    type: STRING
    defaults: "{{ secret('WEAVIATE_API_KEY') }}"


tasks:
  - id: deleteWeaviateMovie
    type: io.kestra.plugin.weaviate.Delete
    url: "{{ inputs.weaviateClusterUrl }}"
    apiKey: "{{ inputs.weaviateApiKey }}"
    className: Movies
    filter:
      name: "The Shawshank Redemption"
```

success is false, nothing got deleted:
![image](https://github.com/kestra-io/plugin-weaviate/assets/86264395/5856f0e0-6175-4eb9-a9c1-2327ecb1e7ad)

### Environment Information

- Kestra Version: 0.13.0
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
