### ISSUE TITLE
BatchCreate task is not creating objects in Weaviate

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-weaviate#54]
### Describe the issue

The BatchCreate task is not able to create the object in Weaviate. Here is a sample flow. The SchemaCreate is successful, and the schema gets created. The BatchCreate task is successful as well, but **no object gets created** in Weaviate.

```
id: weaviate_query
namespace: company.team

tasks:
  - id: query
    type: io.kestra.plugin.weaviate.SchemaCreate
    url: https://<url>.c0.asia-southeast1.gcp.weaviate.cloud
    apiKey: "{{ secret('WEAVIATE_API_KEY') }}"
    className: TestCollection
    fields:
      product_name:
        - string
      product_category:
        - string
      product_subcategory:
        - string
      reviews:
        - string


  - id: write_to_weaviate
    type: io.kestra.plugin.weaviate.BatchCreate
    url: https://<url>.c0.asia-southeast1.gcp.weaviate.cloud
    apiKey: "{{ secret('WEAVIATE_API_KEY') }}"
    className: TestCollection
    objects:
      - product_name: "Test product"
        product_category: "Test category"
        product_subcategory: "Test subcatgory"
        review: "Test review"
```

### Environment

- Kestra Version: 1.19.0
