### ISSUE TITLE
Remove outputs from the Batch-load task — it shouldn't return anything

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-weaviate#9]
### Output Preview cannot be rendered and is not needed

The following will work just fine because both objects have a list of a single key-value pairs (1 column):

```yaml
id: weaviate_query
namespace: dev

tasks:
  - id: batch_load_map
    type: io.kestra.plugin.weaviate.BatchCreate
    url: demo-oczq9ryw.weaviate.network
    apiKey: xxx
    className: Test
    objects: 
      - mynumber: 32
      - mynumber: 64

  - id: extract
    type: io.kestra.plugin.fs.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/ion/ingest.ion

  - id: batch_load
    type: io.kestra.plugin.weaviate.BatchCreate
    url: https://demo-oczq9ryw.weaviate.network
    apiKey: xxx
    className: Titles
    objects: "{{ outputs.extract.uri }}"
```

But try to replace it with objects that have multiple columns and while it doesn't throw any errors, only the last column gets ingested. See reproducer:

```yaml
id: weaviate_query
namespace: dev

tasks:
  - id: batch_load_map
    type: io.kestra.plugin.weaviate.BatchCreate
    url: demo-oczq9ryw.weaviate.network
    apiKey: xxx
    className: Test
    objects: 
      - mynumber: 32
        user: Anna
        city: Berlin
      - mynumber: 64
        user: John
        city: New York

  - id: extract
    type: io.kestra.plugin.fs.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/ion/todos.ion

  - id: batch_load
    type: io.kestra.plugin.weaviate.BatchCreate
    url: https://demo-oczq9ryw.weaviate.network
    apiKey: xxx
    className: Todos
    objects: "{{ outputs.extract.uri }}"
```

![image](https://github.com/kestra-io/plugin-weaviate/assets/86264395/cffb8f2a-7a1b-47aa-b6e8-67a4601a02e6)

![image](https://github.com/kestra-io/plugin-weaviate/assets/86264395/e330cf5a-3707-4f6f-9d19-477f3bf20970)

it should be:

![image](https://github.com/kestra-io/plugin-weaviate/assets/86264395/e03aa3f4-2384-46a1-b19a-28684239221b)
